[nrfconnect] Changes in documentation
LipinskiPNordicSemi/chip-fork pull request #1
Opened 2023-10-17 13:18 UTC by LipinskiPNordicSemi

[nrfconnect] Documentation changes about setting up the environment for nrf examples.

2023-10-18 05:51 UTC, wiba-nordic requested changes
You should also remove the "regardless of the method used for setting up the environment" from the first part in Building.

2023-10-18 05:51 UTC, wiba-nordic commented on examples/lock-app/nrfconnect/README.md
> +4.  When the nRF Connect SDK is installed on your machine. The Install button changes to Open VS Code.
```suggestion
4.  When the nRF Connect SDK is installed on your machine, the Install button changes to the Open VS Code button.
```

2023-10-18 05:51 UTC, wiba-nordic commented on examples/lock-app/nrfconnect/README.md
> +5.  Click the dropdown menu for the installed nRF Connect SDK version.
```suggestion
5.  Click the dropdown menu next to the Open VS Code button for the installed nRF Connect SDK version.
```

2023-10-18 05:51 UTC, wiba-nordic commented on examples/lock-app/nrfconnect/README.md
> +7.  To make sure that ncs is up to date:
```suggestion
7.  Make sure that all parts of the nRF Connect SDK are up to date:
```
How necessary is this step? Shouldn't the Toolchain Manager get everything set up?

2023-10-18 05:51 UTC, wiba-nordic commented on examples/lock-app/nrfconnect/README.md
> +         $ cd {connectedhomeip dirrectory}
```suggestion
         $ cd {connectedhomeip directory}
```

2023-10-18 19:42 UTC, LuDuda reviewed
Thanks! Few comments below.

2023-10-18 19:42 UTC, LuDuda commented on examples/lock-app/nrfconnect/README.md
> +6.  Select Open command prompt.
nit: maybe we can combine this point with previous one?

2023-10-18 19:42 UTC, LuDuda commented on examples/lock-app/nrfconnect/README.md
> +7.  To make sure that ncs is up to date:
It's more to ensure that the nRF Connect SDK revision is compatible with current Matter SDK (connectedhomeip).

So maybe.. "Make sure that nRF Connect SDK version is compatible with Matter SDK"

2023-10-18 19:42 UTC, LuDuda commented on examples/lock-app/nrfconnect/README.md
> +2.  In SDK ENVIRONMENTS, click the Install button next to the [recomended](https://github.com/LipinskiPNordicSemi/chip-fork/blob/documentation/config/nrfconnect/.nrfconnect-recommended-revision) vers
Can we use just a relative path to "config/nrfconnect/.nrfco..." - this is to avoid using external repository.

2023-10-18 19:42 UTC, LuDuda commented on examples/lock-app/nrfconnect/README.md
> +1.  With admin permissions enabled, download and install the nRF [Command Line Tools](https://www.nordicsemi.com/Products/Development-tools/nrf-command-line-tools).
```suggestion
1.  With admin permissions enabled, download and install the [nRF Command Line Tools](https://www.nordicsemi.com/Products/Development-tools/nrf-command-line-tools).
```

2023-10-18 19:42 UTC, LuDuda commented on examples/lock-app/nrfconnect/README.md
> +1.  With admin permissions enabled, download and install the nRF [Command Line Tools](https://www.nordicsemi.com/Products/Development-tools/nrf-command-line-tools).
Btw. Do we need to use "1." here? It's just a single point.

2023-10-18 19:42 UTC, LuDuda commented on examples/lock-app/nrfconnect/README.md
> +2.  In SDK ENVIRONMENTS, click the Install button next to the [recomended](https://github.com/LipinskiPNordicSemi/chip-fork/blob/documentation/config/nrfconnect/.nrfconnect-recommended-revision) vers
also.. In SDK ENVIRONMENTS tab?

Or don't specify it at all, as this is the main tab.. co maybe just: Click the install..

2023-10-18 19:42 UTC, LuDuda commented on examples/lock-app/nrfconnect/README.md
> -Now you can proceed with the [Building](#building) instruction.
Should we leave this line :)

2023-10-18 19:42 UTC, LuDuda commented on examples/lock-app/nrfconnect/README.md
> +6.  Select Open command prompt.
I think it's called "Open terminal" on Linux if i'm not mistaken - can you please check?

Side note: Can we do sth like: `Open terminal` (adding ` character before and after) or **Open terminal** (adding two * to bold it).

2023-10-19 05:19 UTC, wiba-nordic commented on examples/lock-app/nrfconnect/README.md
> +2.  In SDK ENVIRONMENTS, click the Install button next to the [recomended](https://github.com/LipinskiPNordicSemi/chip-fork/blob/documentation/config/nrfconnect/.nrfconnect-recommended-revision) vers
The official installation instructions in https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/installation/assistant.html#install-toolchain-manager uses "In SDK ENVIRONMENTS", so it's fine as is. But I would be fine with starting "Click the Install button..."

2023-10-19 05:30 UTC, wiba-nordic commented on examples/lock-app/nrfconnect/README.md
> +7.  To make sure that ncs is up to date:
Could probably go even more specific:
```suggestion
7. Make sure that the nRF Connect SDK version is compatible with the Matter SDK version:
```

2023-10-19 05:31 UTC, wiba-nordic commented on examples/lock-app/nrfconnect/README.md
> +1.  With admin permissions enabled, download and install the nRF [Command Line Tools](https://www.nordicsemi.com/Products/Development-tools/nrf-command-line-tools).
Very good point. Don't really need to number a single step.

2023-10-19 12:52 UTC, wiba-nordic requested changes

2023-10-19 12:52 UTC, wiba-nordic commented on examples/lock-app/nrfconnect/README.md
> +3.  In the **APPS** section, click `Install` next to Toolchain Manager.
```suggestion
3.  In the **APPS** section, click **Install** next to Toolchain Manager.
```
I'm not sure if there are other guidelines for CHIP, so suggesting what we use for formatting in other Markdown docs.

2023-10-19 12:52 UTC, wiba-nordic commented on examples/lock-app/nrfconnect/README.md
> +2.  Click the `Install` button next to the [recommended](../../../config/nrfconnect/.nrfconnect-recommended-revision) version of the nRF Connect SDK.
```suggestion
2.  Click the **Install** button next to the [recommended](../../../config/nrfconnect/.nrfconnect-recommended-revision) version of the nRF Connect SDK.
```

2023-10-19 12:52 UTC, wiba-nordic commented on examples/lock-app/nrfconnect/README.md
> +    `Change directory` button. Otherwise, click the `Continue installation button`.
```suggestion
    **Change directory** button. Otherwise, click the **Continue installation** button.
```

2023-10-19 12:52 UTC, wiba-nordic commented on examples/lock-app/nrfconnect/README.md
> +4.  When the nRF Connect SDK is installed on your machine, the Install button changes to the Open VS Code button.
```suggestion
4.  When the nRF Connect SDK is installed on your machine, the **Install** button changes to the **Open VS Code** button.
```

2023-10-19 12:52 UTC, wiba-nordic commented on examples/lock-app/nrfconnect/README.md
> +5.  Click the dropdown menu next to the Open VS Code button for the installed nRF Connect SDK version, and select `Open terminal`.
```suggestion
5.  Click the dropdown menu next to the Open VS Code button for the installed nRF Connect SDK version, and select **Open terminal**.
```

2023-10-23 06:59 UTC, wiba-nordic reviewed
I can't comment on Lines 309 - 310 (old, Lines 350 - 351), but since there is now only one method described, they should be changed to:
```
Complete the following steps to build the sample:
```

2023-10-23 09:16 UTC, wiba-nordic approved these changes

2023-10-23 14:20 UTC, merged